service: simple-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-1
  logs:
    restApi:
      accessLogging: false # Optional configuration which enables or disables access logging. Defaults to true.
      executionLogging: true


functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: post